### ISSUE TITLE
French translations

### ISSUE THREAD

**Issue by Anne017** [Styrkur/styrkur-app#3]
Hello,
Thanks for your amazing work!
Is this app already translated in French for Ubuntu (I can't check since I don't have an Ubuntu Phone/Tablet)?
If no, I can help with the French translations, just tell me which files need to be modified.

**Comment by aevare** [comment]
Hi Anne! 
Glad you like the app.
I don't have an French translation, but it would be great to get one!

You can create a pull request with a file: www/js/translations/fr.js or just send it to me.
Please use the english translation as a template:
https://github.com/Styrkur/styrkur-app/blob/master/www/js/translations/en.js
